# Generated by Django 5.0.6 on 2024-05-31 22:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pols', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
