# Generated by Django 5.0.6 on 2024-06-07 17:12

import django.db.models.deletion
import django_mysql.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pols', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255)),
                ('count_rooms', models.IntegerField()),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('CSI', models.FloatField()),
                ('stars', models.FloatField(null=True)),
                ('description', models.TextField(null=True)),
                ('img1', django_mysql.models.SizedTextField(size_class=3)),
                ('img2', django_mysql.models.SizedTextField(size_class=3)),
                ('img3', django_mysql.models.SizedTextField(size_class=3)),
                ('img4', django_mysql.models.SizedTextField(size_class=3)),
                ('img5', django_mysql.models.SizedTextField(size_class=3)),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16)),
                ('validity_period', models.DateField()),
                ('CVV', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pols.hotel')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='favorites_hotel',
            field=models.ManyToManyField(through='pols.Favorites', to='pols.hotel'),
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('beds_amount', models.IntegerField()),
                ('bath_amount', models.IntegerField()),
                ('s', models.IntegerField(null=True)),
                ('description', models.TextField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img1', django_mysql.models.SizedTextField(null=True, size_class=3)),
                ('img2', django_mysql.models.SizedTextField(null=True, size_class=3)),
                ('img3', django_mysql.models.SizedTextField(null=True, size_class=3)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pols.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('description', models.TextField()),
                ('rooms', models.ManyToManyField(to='pols.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_people', models.IntegerField()),
                ('arrival', models.DateTimeField()),
                ('departure', models.DateTimeField()),
                ('price_per_room', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_services', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pols.rooms')),
            ],
        ),
    ]
