# Generated by Django 5.0.6 on 2024-06-05 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pols', '0002_hotel_imagesrooms_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageshotels',
            name='hotel',
        ),
        migrations.DeleteModel(
            name='ImagesRooms',
        ),
        migrations.DeleteModel(
            name='ImagesHotels',
        ),
    ]
