# Generated by Django 5.0.6 on 2024-06-07 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pols', '0002_hotel_alter_user_managers_alter_user_username_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='phone',
        ),
    ]
