# Generated by Django 5.0.6 on 2024-06-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pols', '0003_remove_imageshotels_hotel_delete_imagesrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
