# Generated by Django 5.0.6 on 2024-06-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pols', '0003_remove_hotel_email_remove_hotel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='min_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
