# Generated by Django 5.0.6 on 2024-06-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pols', '0004_favorites_min_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.IntegerField(null=True),
        ),
    ]
