# Generated by Django 5.0.6 on 2024-06-05 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pols', '0004_hotel_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='img3',
        ),
    ]
