# Generated by Django 5.0.6 on 2024-06-05 18:27

import django_mysql.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pols', '0005_remove_rooms_img1_remove_rooms_img2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='img1',
            field=django_mysql.models.SizedTextField(null=True, size_class=3),
        ),
        migrations.AddField(
            model_name='rooms',
            name='img2',
            field=django_mysql.models.SizedTextField(null=True, size_class=3),
        ),
        migrations.AddField(
            model_name='rooms',
            name='img3',
            field=django_mysql.models.SizedTextField(null=True, size_class=3),
        ),
    ]
